# Firefox and Chromium tests (modified to remove \r, \n, and spaces.

firefox_values = [
  [ '' ],
  [ "foo@bar.com"],
  [ "foo@bar.com"],
  [ "foo@bar.com "],
  [ "foo@bar.com"],
  [ "foo@bar.com "],
  [ "foo@bar.com   "],
  [ "foo@bar.com   "],
  [ "tulip"],

  [ "@bar.com"],
  [ "foo@bar.com"],
  [ "foo@bar.com"],
  [ "foo@bar.com"],
  [ "fü@foo.com"],

  [ "foo@bar"],
  [ "foo@b"],
  [ "foo@"],
  [ "foo@bar."],
  [ "foo@foo.bar"],
  [ "foo@foo..bar"],
  [ "foo@.bar"],
  [ "foo@tulip.foo.bar"],
  [ "foo@tulip.foo-bar"],
  [ "foo@1.2"],
  [ "foo@127.0.0.1"],
  [ "foo@1.2.3"],
  [ "foo@bar.com"],
  [ "foo@bar.com"],
  [ "foo@bar.com"],
  [ "foo@."],
  [ "foo@fü.com"],
  [ "foo@fu.cüm"],
  [ "thisUsernameIsLongerThanSixtyThreeCharactersInLengthRightAboutNow@mozilla.tld"],

  [ "this.is.email.should.be.longer.than.sixty.four.characters.föö@mözillä.tld"],
  [ "this-is-email-should-be-longer-than-sixty-four-characters-föö@mözillä.tld"],

  [ "foo@thislabelisexactly63characterssssssssssssssssssssssssssssssssss"],
  [ "foo@thislabelisexactly63characterssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thislabelisexactly63characterssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thislabelisexactly63characterssssssssssssssssssssssssssssssssss"],
  [ "foo@thislabelisexactly64charactersssssssssssssssssssssssssssssssssss"],
  [ "foo@thislabelisexactly64charactersssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thislabelisexactly64charactersssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thislabelisexactly64charactersssssssssssssssssssssssssssssssssss"],

  [ "foo@thisläbelisexäctly63charäcterssssssssssssssssssssssssssssssssss"],
  [ "foo@thisläbelisexäctly63charäcterssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thisläbelisexäctly63charäcterssssssssssssssssssssssssssssssssss.com"],
  [ "foo@foo.thisläbelisexäctly63charäcterssssssssssssssssssssssssssssssssss"],

  [ "foo@foo-bar"],
  [ "foo@-foo"],
  [ "foo@foo-.bar"],
  [ "foo@-.-"],
  [ "foo@fo-o.bar"],
  [ "foo@fo-o.-bar"],
  [ "foo@fo-o.bar-"],
  [ "foo@fo-o.-"],
  [ "foo@fo--o"],
]

chromium_values = [
["something@something.com", "something@something.com", "expectValid"],
["someone@localhost.localdomain", "someone@localhost.localdomain", "expectValid"],
["someone@127.0.0.1", "someone@127.0.0.1", "expectValid"],
["a@b.b", "a@b.b", "expectValid"],
["a/b@domain.com", "a/b@domain.com", "expectValid"],
["{}@domain.com", "{}@domain.com", "expectValid"],
["m*'!%@something.sa", "m*'!%@something.sa", "expectValid"],
["tu!!7n7.ad##0!!!@company.ca", "tu!!7n7.ad##0!!!@company.ca", "expectValid"],
["%@com.com", "%@com.com", "expectValid"],
["!#$%&'*+/=?^_`{|}~.-@com.com", "!#$%&'*+/=?^_`{|}~.-@com.com", "expectValid"],
[".wooly@example.com", ".wooly@example.com", "expectValid"],
["wo..oly@example.com", "wo..oly@example.com", "expectValid"],
["someone@do-ma-in.com", "someone@do-ma-in.com", "expectValid"],
["somebody@example", "somebody@example", "expectValid"],
["\u000Aa@p.com\u000A", "a@p.com", "expectValid"],
["\u000Da@p.com\u000D", "a@p.com", "expectValid"],
["a\u000A@p.com", "a@p.com", "expectValid"],
["a\u000D@p.com", "a@p.com", "expectValid"],
["", "", "expectValid"],
[" ", "", "expectValid"],
[" a@p.com", "a@p.com", "expectValid"],
["a@p.com ", "a@p.com", "expectValid"],
[" a@p.com ", "a@p.com", "expectValid"],
["\u0020a@p.com\u0020", "a@p.com", "expectValid"],
["\u0009a@p.com\u0009", "a@p.com", "expectValid"],
["\u000Ca@p.com\u000C", "a@p.com", "expectValid"],

["invalid:email@example.com", "invalid:email@example.com", "expectInvalid"],
["@somewhere.com", "@somewhere.com", "expectInvalid"],
["example.com", "example.com", "expectInvalid"],
["@@example.com", "@@example.com", "expectInvalid"],
["a space@example.com", "a space@example.com", "expectInvalid"],
["something@ex..ample.com", "something@ex..ample.com", "expectInvalid"],
["a\b@c", "a\b@c", "expectInvalid"],
["someone@somewhere.com.", "someone@somewhere.com.", "expectInvalid"],
["\"\"test\blah\"\"@example.com", "\"\"test\blah\"\"@example.com", "expectInvalid"],
["\"testblah\"@example.com", "\"testblah\"@example.com", "expectInvalid"],
["someone@somewhere.com@", "someone@somewhere.com@", "expectInvalid"],
["someone@somewhere_com", "someone@somewhere_com", "expectInvalid"],
["someone@some:where.com", "someone@some:where.com", "expectInvalid"],
[".", ".", "expectInvalid"],
["F/s/f/a@feo+re.com", "F/s/f/a@feo+re.com", "expectInvalid"],
["some+long+email+address@some+host-weird-/looking.com", "some+long+email+address@some+host-weird-/looking.com", "expectInvalid"],
["a @p.com", "a @p.com", "expectInvalid"],
["a\u0020@p.com", "a\u0020@p.com", "expectInvalid"],
["a\u0009@p.com", "a\u0009@p.com", "expectInvalid"],
["a\u000B@p.com", "a\u000B@p.com", "expectInvalid"],
["a\u000C@p.com", "a\u000C@p.com", "expectInvalid"],
["a\u2003@p.com", "a\u2003@p.com", "expectInvalid"],
["a\u3000@p.com", "a\u3000@p.com", "expectInvalid"],
["ddjk-s-jk@asl-.com", "ddjk-s-jk@asl-.com", "expectInvalid"],
["someone@do-.com", "someone@do-.com", "expectInvalid"],
["somebody@-p.com", "somebody@-p.com", "expectInvalid"],
["somebody@-.com", "somebody@-.com", "expectInvalid"],

["something@something.com", "something@something.com", "expectValid"],
["someone@localhost.localdomain", "someone@localhost.localdomain", "expectValid"],
["someone@127.0.0.1", "someone@127.0.0.1", "expectValid"],
["a@b.b", "a@b.b", "expectValid"],
["a/b@domain.com", "a/b@domain.com", "expectValid"],
["{}@domain.com", "{}@domain.com", "expectValid"],
["m*'!%@something.sa", "m*'!%@something.sa", "expectValid"],
["tu!!7n7.ad##0!!!@company.ca", "tu!!7n7.ad##0!!!@company.ca", "expectValid"],
["%@com.com", "%@com.com", "expectValid"],
["!#$%&'*+/=?^_`{|}~.-@com.com", "!#$%&'*+/=?^_`{|}~.-@com.com", "expectValid"],
[".wooly@example.com", ".wooly@example.com", "expectValid"],
["wo..oly@example.com", "wo..oly@example.com", "expectValid"],
["someone@do-ma-in.com", "someone@do-ma-in.com", "expectValid"],
["somebody@example", "somebody@example", "expectValid"],
["\u0020a@p.com\u0020", "a@p.com", "expectValid"],
["\u0009a@p.com\u0009", "a@p.com", "expectValid"],
["\u000Aa@p.com\u000A", "a@p.com", "expectValid"],
["\u000Ca@p.com\u000C", "a@p.com", "expectValid"],
["\u000Da@p.com\u000D", "a@p.com", "expectValid"],
["a\u000A@p.com", "a@p.com", "expectValid"],
["a\u000D@p.com", "a@p.com", "expectValid"],
["", "", "expectValid"],
[" ", "", "expectValid"],
[" a@p.com", "a@p.com", "expectValid"],
["a@p.com ", "a@p.com", "expectValid"],
[" a@p.com ", "a@p.com", "expectValid"],

["invalid:email@example.com", "invalid:email@example.com", "expectInvalid"],
["@somewhere.com", "@somewhere.com", "expectInvalid"],
["example.com", "example.com", "expectInvalid"],
["@@example.com", "@@example.com", "expectInvalid"],
["a space@example.com", "a space@example.com", "expectInvalid"],
["something@ex..ample.com", "something@ex..ample.com", "expectInvalid"],
["a\b@c", "a\b@c", "expectInvalid"],
["someone@somewhere.com.", "someone@somewhere.com.", "expectInvalid"],
["\"\"test\blah\"\"@example.com", "\"\"test\blah\"\"@example.com", "expectInvalid"],
["\"testblah\"@example.com", "\"testblah\"@example.com", "expectInvalid"],
["someone@somewhere.com@", "someone@somewhere.com@", "expectInvalid"],
["someone@somewhere_com", "someone@somewhere_com", "expectInvalid"],
["someone@some:where.com", "someone@some:where.com", "expectInvalid"],
[".", ".", "expectInvalid"],
["F/s/f/a@feo+re.com", "F/s/f/a@feo+re.com", "expectInvalid"],
["some+long+email+address@some+host-weird-/looking.com", "some+long+email+address@some+host-weird-/looking.com", "expectInvalid"],
["\u000Ba@p.com\u000B", "\u000Ba@p.com\u000B", "expectInvalid"],
["\u2003a@p.com\u2003", "\u2003a@p.com\u2003", "expectInvalid"],
["\u3000a@p.com\u3000", "\u3000a@p.com\u3000", "expectInvalid"],
["a @p.com", "a @p.com", "expectInvalid"],
["a\u0020@p.com", "a\u0020@p.com", "expectInvalid"],
["a\u0009@p.com", "a\u0009@p.com", "expectInvalid"],
["a\u000B@p.com", "a\u000B@p.com", "expectInvalid"],
["a\u000C@p.com", "a\u000C@p.com", "expectInvalid"],
["a\u2003@p.com", "a\u2003@p.com", "expectInvalid"],
["a\u3000@p.com", "a\u3000@p.com", "expectInvalid"],
["ddjk-s-jk@asl-.com", "ddjk-s-jk@asl-.com", "expectInvalid"],
["someone@do-.com", "someone@do-.com", "expectInvalid"],
["somebody@-p.com", "somebody@-p.com", "expectInvalid"],
["somebody@-.com", "somebody@-.com", "expectInvalid"],

["someone@somewhere.com,john@doe.com,a@b.c,a/b@c.c,ualla@ualla.127", "someone@somewhere.com,john@doe.com,a@b.c,a/b@c.c,ualla@ualla.127", "expectValid"],
["tu!!7n7.ad##0!!!@company.ca,F/s/f/a@feo-re.com,m*'@a.b", "tu!!7n7.ad##0!!!@company.ca,F/s/f/a@feo-re.com,m*'@a.b", "expectValid"],
[" a@p.com,b@p.com", "a@p.com,b@p.com", "expectValid"],
["a@p.com ,b@p.com", "a@p.com,b@p.com", "expectValid"],
["a@p.com, b@p.com", "a@p.com,b@p.com", "expectValid"],
["a@p.com,b@p.com ", "a@p.com,b@p.com", "expectValid"],
["   a@p.com   ,   b@p.com   ", "a@p.com,b@p.com", "expectValid"],
["\u0020a@p.com\u0020,\u0020b@p.com\u0020", "a@p.com,b@p.com", "expectValid"],
["\u0009a@p.com\u0009,\u0009b@p.com\u0009", "a@p.com,b@p.com", "expectValid"],
["\u000Aa@p.com\u000A,\u000Ab@p.com\u000A", "a@p.com,b@p.com", "expectValid"],
["\u000Ca@p.com\u000C,\u000Cb@p.com\u000C", "a@p.com,b@p.com", "expectValid"],
["\u000Da@p.com\u000D,\u000Db@p.com\u000D", "a@p.com,b@p.com", "expectValid"],

["someone@somewhere.com,john@doe..com,a@b,a/b@c,ualla@ualla.127", "someone@somewhere.com,john@doe..com,a@b,a/b@c,ualla@ualla.127", "expectInvalid"],
["some+long+email+address@some+host:weird-/looking.com,F/s/f/a@feo+re.com,,m*'@'!%", "some+long+email+address@some+host:weird-/looking.com,F/s/f/a@feo+re.com,,m*'@'!%", "expectInvalid"],
["   a @p.com   ,   b@p.com   ", "a @p.com,b@p.com", "expectInvalid"],
["   a@p.com   ,   b @p.com   ", "a@p.com,b @p.com", "expectInvalid"],
["\u000Ba@p.com\u000B,\u000Bb@p.com\u000B", "\u000Ba@p.com\u000B,\u000Bb@p.com\u000B", "expectInvalid"],
["\u2003a@p.com\u2003,\u2003b@p.com\u2003", "\u2003a@p.com\u2003,\u2003b@p.com\u2003", "expectInvalid"],
["\u3000a@p.com\u3000,\u3000b@p.com\u3000", "\u3000a@p.com\u3000,\u3000b@p.com\u3000", "expectInvalid"],
[",,", ",,", "expectInvalid"],
[" ,,", ",,", "expectInvalid"],
[", ,", ",,", "expectInvalid"],
[",, ", ",,", "expectInvalid"],
["  ,  ,  ", ",,", "expectInvalid"],
["\u0020,\u0020,\u0020", ",,", "expectInvalid"],
["\u0009,\u0009,\u0009", ",,", "expectInvalid"],
["\u000A,\u000A,\u000A", ",,", "expectInvalid"],
["\u000B,\u000B,\u000B", "\u000B,\u000B,\u000B", "expectInvalid"],
["\u000C,\u000C,\u000C", ",,", "expectInvalid"],
["\u000D,\u000D,\u000D", ",,", "expectInvalid"],
["\u2003,\u2003,\u2003", "\u2003,\u2003,\u2003", "expectInvalid"],
["\u3000,\u3000,\u3000", "\u3000,\u3000,\u3000", "expectInvalid"]]

